### ISSUE TITLE
大佬可以顺手把N1的固件也放到这里吗？

### ISSUE THREAD

**Issue by luckyreny** [skytotwo/NanoPi-R1S-Build-By-Actions#15]
RT

**Comment by CWZ7605** [comment]
大佬这是专门针对R1S做的action。N1的话，大佬更有可能是开一个新的repo。

**Comment by skytotwo** [comment]
n1的固件网上太多啦，r1s固件还有教程网上太少，你要n1固件的话，回头我找下发给你，有比较新的

**Comment by luckyreny** [comment]
谢谢大佬。看来我想简单了，以为和编译其它的一样只要在编译时选择一下就好。可能源码都不同吧。
