### ISSUE TITLE
6in4 missing in LuCi

### ISSUE THREAD

**Issue by lcsaszar** [skytotwo/NanoPi-R1S-Build-By-Actions#18]
Hello, I am trying to setup HE net 6in4 tunnel on NanoPI R1S-H5. I installed luci-proto-ipv6 and 6in4, but the 6in4 option is still missing on the WAN6 interface configuration page.

root@FriendlyWrt:~# uname -a
Linux FriendlyWrt 4.14.111 #1 SMP Mon Dec 23 18:18:09 CST 2019 aarch64 GNU/Linux
OpenWrt SNAPSHOT r11626-16e87514f5 / LuCI friendlywrt branch git-19.343.40425-bb021b4

Thanks

**Comment by skytotwo** [comment]
Have you installed radvd?

**Comment by lcsaszar** [comment]
I could add the package manually.
