### ISSUE TITLE
r1s h5版本固件没有无线

### ISSUE THREAD

**Issue by matri** [skytotwo/NanoPi-R1S-Build-By-Actions#2]
比较奇怪，我fork以后自己编译，或者直接在本repo的actions里面下载编译好的固件，刷到r1s h5里面都没wifi，硬件没有问题，其他固件都有无线，请问是上游代码问题还是有什么配置需要修改的吗？谢谢！

**Comment by skytotwo** [comment]
是因为我没有加入，本意觉得无线鸡肋。现在你重新拉取最新的代码看下，主分支已经更新openwrt版本为19.07，也有了无线，加入了trojan，smartdns等，插件很全。

**Comment by skytotwo** [comment]
> 比较奇怪，我fork以后自己编译，或者直接在本repo的actions里面下载编译好的固件，刷到r1s h5里面都没wifi，硬件没有问题，其他固件都有无线，请问是上游代码问题还是有什么配置需要修改的吗？谢谢！

是因为我没有加入，本意觉得无线鸡肋。现在你重新拉取最新的代码看下，主分支已经更新openwrt版本为19.07，也有了无线，加入了trojan，smartdns等，插件很全。

**Comment by matri** [comment]
明白了，感谢，我重新拉一下。
