### ISSUE TITLE
可否加入对R2S的支持

### ISSUE THREAD

**Issue by ghost** [skytotwo/NanoPi-R1S-Build-By-Actions#23]
最近RS2要发货了,看起来是真香,不知道是否可以添加对于R2S的支持

**Comment by skytotwo** [comment]
> 最近RS2要发货了,看起来是真香,不知道是否可以添加对于R2S的支持

据说样机测试对比过，r2s的rk3328并没有比h5强哦，编译其实也不难，如果家里带宽300以内，r1s是更好的选择的，性能其实更好，而且带一个弱鸡wifi

**Comment by ghost** [comment]
> > 最近RS2要发货了,看起来是真香,不知道是否可以添加对于R2S的支持
> 
> 据说样机测试对比过，r2s的rk3328并没有比h5强哦，编译其实也不难，如果家里带宽300以内，r1s是更好的选择的，性能其实更好，而且带一个弱鸡wifi

原来如此,看来rk3328还是强在多媒体解码 , 感谢解答
